default['zabbix']['config_file2'] = '/etc/zabbix/zabbix_agentd.d/'
default['zabbix']['scan_dir'] = '/tmp/nickTemp2/'
default['zabbix']['user_param1'] = 'UserParameter=nickTest.nickCount,ls -l '
default['zabbix']['user_param2'] = ' | wc -l'
default['zabbix']['script_dir'] = '/etc/zabbix/nickTemp/'
